/* Automatically @generated by tree-sitter v0.25.5 (460118b4c82318b083b4d527c9c750426730f9c0) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 31
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 16
#define ALIAS_COUNT 0
#define TOKEN_COUNT 9
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_date_header_token1 = 1,
  sym_date = 2,
  sym_description = 3,
  sym_account = 4,
  sym_quantity = 5,
  sym_comment = 6,
  aux_sym_comment_line_token1 = 7,
  sym__newline = 8,
  sym_source_file = 9,
  sym_day = 10,
  sym_date_header = 11,
  sym_entry = 12,
  sym_comment_line = 13,
  aux_sym_source_file_repeat1 = 14,
  aux_sym_day_repeat1 = 15,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_date_header_token1] = "date_header_token1",
  [sym_date] = "date",
  [sym_description] = "description",
  [sym_account] = "account",
  [sym_quantity] = "quantity",
  [sym_comment] = "comment",
  [aux_sym_comment_line_token1] = "comment_line_token1",
  [sym__newline] = "_newline",
  [sym_source_file] = "source_file",
  [sym_day] = "day",
  [sym_date_header] = "date_header",
  [sym_entry] = "entry",
  [sym_comment_line] = "comment_line",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_day_repeat1] = "day_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_date_header_token1] = aux_sym_date_header_token1,
  [sym_date] = sym_date,
  [sym_description] = sym_description,
  [sym_account] = sym_account,
  [sym_quantity] = sym_quantity,
  [sym_comment] = sym_comment,
  [aux_sym_comment_line_token1] = aux_sym_comment_line_token1,
  [sym__newline] = sym__newline,
  [sym_source_file] = sym_source_file,
  [sym_day] = sym_day,
  [sym_date_header] = sym_date_header,
  [sym_entry] = sym_entry,
  [sym_comment_line] = sym_comment_line,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_day_repeat1] = aux_sym_day_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_date_header_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_date] = {
    .visible = true,
    .named = true,
  },
  [sym_description] = {
    .visible = true,
    .named = true,
  },
  [sym_account] = {
    .visible = true,
    .named = true,
  },
  [sym_quantity] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_comment_line_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_day] = {
    .visible = true,
    .named = true,
  },
  [sym_date_header] = {
    .visible = true,
    .named = true,
  },
  [sym_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_day_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 14,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 24,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      if (lookahead == '\n') ADVANCE(56);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') SKIP(0);
      if (lookahead == '#') ADVANCE(55);
      if (lookahead == '*') ADVANCE(16);
      if (lookahead == ',') ADVANCE(39);
      if (lookahead == '.') ADVANCE(26);
      if (lookahead == ';') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(47);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(56);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(56);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') SKIP(2);
      if (lookahead == ',') ADVANCE(10);
      if (lookahead == '.') ADVANCE(50);
      if (lookahead == ';') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(56);
      if (lookahead == '\r') ADVANCE(23);
      if (lookahead == ' ') ADVANCE(22);
      if (lookahead == ';') ADVANCE(54);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 4:
      if (('-' <= lookahead && lookahead <= '/')) ADVANCE(8);
      END_STATE();
    case 5:
      if (('-' <= lookahead && lookahead <= '/')) ADVANCE(9);
      END_STATE();
    case 6:
      if (('-' <= lookahead && lookahead <= '/')) ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 13:
      if (eof) ADVANCE(15);
      if (lookahead == '\n') ADVANCE(56);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') SKIP(13);
      if (lookahead == '*') ADVANCE(17);
      if (lookahead == '#' ||
          lookahead == ';') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      if (lookahead == '\n') ADVANCE(56);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') SKIP(14);
      if (lookahead == '*') ADVANCE(16);
      if (lookahead == '#' ||
          lookahead == ';') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(47);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_date_header_token1);
      if (lookahead == '*') ADVANCE(16);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(38);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_date_header_token1);
      if (lookahead == '*') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_date);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_date);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(47);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_date);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_date);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(47);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_description);
      if (lookahead == '\n') ADVANCE(56);
      if (lookahead == '\r') ADVANCE(23);
      if (lookahead == ' ') ADVANCE(22);
      if (lookahead == ';') ADVANCE(54);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_description);
      if (lookahead == '\n') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != ';') ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_description);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_account);
      if (lookahead == ',') ADVANCE(39);
      if (lookahead == '.') ADVANCE(40);
      if (('-' <= lookahead && lookahead <= '/')) ADVANCE(41);
      if (lookahead == 'h' ||
          lookahead == 'm') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(47);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_account);
      if (lookahead == '.') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(47);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_account);
      if (lookahead == '.') ADVANCE(27);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(47);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_account);
      if (lookahead == 'h') ADVANCE(47);
      if (('-' <= lookahead && lookahead <= '/')) ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(47);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_account);
      if (lookahead == 'h') ADVANCE(47);
      if (('-' <= lookahead && lookahead <= '/')) ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(47);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_account);
      if (lookahead == 'h') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(47);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_account);
      if (lookahead == ',' ||
          lookahead == '.') ADVANCE(39);
      if (lookahead == 'h' ||
          lookahead == 'm') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(47);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_account);
      if (lookahead == ',' ||
          lookahead == '.') ADVANCE(39);
      if (lookahead == 'h' ||
          lookahead == 'm') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(47);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_account);
      if (lookahead == ',' ||
          lookahead == '.') ADVANCE(39);
      if (lookahead == 'h' ||
          lookahead == 'm') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(47);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_account);
      if (lookahead == ',' ||
          lookahead == '.') ADVANCE(39);
      if (lookahead == 'h' ||
          lookahead == 'm') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(47);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_account);
      if (('-' <= lookahead && lookahead <= '/')) ADVANCE(41);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(47);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_account);
      if (('-' <= lookahead && lookahead <= '/')) ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(47);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_account);
      if (('-' <= lookahead && lookahead <= '/')) ADVANCE(42);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(47);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_account);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_account);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(47);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_account);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(47);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_account);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(47);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_account);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(47);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_account);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(47);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_account);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(47);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_account);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(47);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_account);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_account);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_quantity);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_quantity);
      if (lookahead == '.') ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_quantity);
      if (lookahead == '.') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_quantity);
      if (lookahead == 'h') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_quantity);
      if (lookahead == ',' ||
          lookahead == '.') ADVANCE(10);
      if (lookahead == 'h' ||
          lookahead == 'm') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_quantity);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_comment_line_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 13},
  [2] = {.lex_state = 13},
  [3] = {.lex_state = 14},
  [4] = {.lex_state = 14},
  [5] = {.lex_state = 13},
  [6] = {.lex_state = 14},
  [7] = {.lex_state = 14},
  [8] = {.lex_state = 14},
  [9] = {.lex_state = 14},
  [10] = {.lex_state = 14},
  [11] = {.lex_state = 14},
  [12] = {.lex_state = 14},
  [13] = {.lex_state = 14},
  [14] = {.lex_state = 14},
  [15] = {.lex_state = 13},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 13},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_date_header_token1] = ACTIONS(1),
    [sym_date] = ACTIONS(1),
    [sym_account] = ACTIONS(1),
    [sym_quantity] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [aux_sym_comment_line_token1] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(25),
    [sym_day] = STATE(2),
    [sym_date_header] = STATE(3),
    [sym_comment_line] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_date_header_token1] = ACTIONS(5),
    [sym_date] = ACTIONS(7),
    [aux_sym_comment_line_token1] = ACTIONS(9),
    [sym__newline] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym_day] = STATE(5),
    [sym_date_header] = STATE(3),
    [sym_comment_line] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(13),
    [aux_sym_date_header_token1] = ACTIONS(5),
    [sym_date] = ACTIONS(7),
    [aux_sym_comment_line_token1] = ACTIONS(9),
    [sym__newline] = ACTIONS(15),
  },
  [STATE(3)] = {
    [sym_entry] = STATE(4),
    [sym_comment_line] = STATE(4),
    [aux_sym_day_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(17),
    [aux_sym_date_header_token1] = ACTIONS(19),
    [sym_date] = ACTIONS(19),
    [sym_account] = ACTIONS(21),
    [aux_sym_comment_line_token1] = ACTIONS(23),
    [sym__newline] = ACTIONS(17),
  },
  [STATE(4)] = {
    [sym_entry] = STATE(6),
    [sym_comment_line] = STATE(6),
    [aux_sym_day_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(25),
    [aux_sym_date_header_token1] = ACTIONS(27),
    [sym_date] = ACTIONS(27),
    [sym_account] = ACTIONS(21),
    [aux_sym_comment_line_token1] = ACTIONS(23),
    [sym__newline] = ACTIONS(25),
  },
  [STATE(5)] = {
    [sym_day] = STATE(5),
    [sym_date_header] = STATE(3),
    [sym_comment_line] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(29),
    [aux_sym_date_header_token1] = ACTIONS(31),
    [sym_date] = ACTIONS(34),
    [aux_sym_comment_line_token1] = ACTIONS(37),
    [sym__newline] = ACTIONS(40),
  },
  [STATE(6)] = {
    [sym_entry] = STATE(6),
    [sym_comment_line] = STATE(6),
    [aux_sym_day_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(43),
    [aux_sym_date_header_token1] = ACTIONS(45),
    [sym_date] = ACTIONS(45),
    [sym_account] = ACTIONS(47),
    [aux_sym_comment_line_token1] = ACTIONS(50),
    [sym__newline] = ACTIONS(43),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(53), 2,
      ts_builtin_sym_end,
      sym__newline,
    ACTIONS(55), 4,
      aux_sym_date_header_token1,
      sym_date,
      sym_account,
      aux_sym_comment_line_token1,
  [11] = 2,
    ACTIONS(57), 2,
      ts_builtin_sym_end,
      sym__newline,
    ACTIONS(59), 4,
      aux_sym_date_header_token1,
      sym_date,
      sym_account,
      aux_sym_comment_line_token1,
  [22] = 2,
    ACTIONS(61), 2,
      ts_builtin_sym_end,
      sym__newline,
    ACTIONS(63), 4,
      aux_sym_date_header_token1,
      sym_date,
      sym_account,
      aux_sym_comment_line_token1,
  [33] = 2,
    ACTIONS(65), 2,
      ts_builtin_sym_end,
      sym__newline,
    ACTIONS(67), 4,
      aux_sym_date_header_token1,
      sym_date,
      sym_account,
      aux_sym_comment_line_token1,
  [44] = 2,
    ACTIONS(69), 2,
      ts_builtin_sym_end,
      sym__newline,
    ACTIONS(71), 4,
      aux_sym_date_header_token1,
      sym_date,
      sym_account,
      aux_sym_comment_line_token1,
  [55] = 2,
    ACTIONS(73), 2,
      ts_builtin_sym_end,
      sym__newline,
    ACTIONS(75), 4,
      aux_sym_date_header_token1,
      sym_date,
      sym_account,
      aux_sym_comment_line_token1,
  [66] = 2,
    ACTIONS(77), 2,
      ts_builtin_sym_end,
      sym__newline,
    ACTIONS(79), 4,
      aux_sym_date_header_token1,
      sym_date,
      sym_account,
      aux_sym_comment_line_token1,
  [77] = 2,
    ACTIONS(81), 2,
      ts_builtin_sym_end,
      sym__newline,
    ACTIONS(83), 4,
      aux_sym_date_header_token1,
      sym_date,
      sym_account,
      aux_sym_comment_line_token1,
  [88] = 2,
    ACTIONS(83), 2,
      aux_sym_date_header_token1,
      aux_sym_comment_line_token1,
    ACTIONS(81), 3,
      ts_builtin_sym_end,
      sym_date,
      sym__newline,
  [98] = 3,
    ACTIONS(85), 1,
      sym_description,
    ACTIONS(87), 1,
      sym_comment,
    ACTIONS(89), 1,
      sym__newline,
  [108] = 3,
    ACTIONS(91), 1,
      sym_description,
    ACTIONS(93), 1,
      sym_comment,
    ACTIONS(95), 1,
      sym__newline,
  [118] = 3,
    ACTIONS(97), 1,
      sym_quantity,
    ACTIONS(99), 1,
      sym_comment,
    ACTIONS(101), 1,
      sym__newline,
  [128] = 2,
    ACTIONS(103), 1,
      sym_comment,
    ACTIONS(105), 1,
      sym__newline,
  [135] = 2,
    ACTIONS(107), 1,
      sym_comment,
    ACTIONS(109), 1,
      sym__newline,
  [142] = 2,
    ACTIONS(111), 1,
      sym_comment,
    ACTIONS(113), 1,
      sym__newline,
  [149] = 1,
    ACTIONS(115), 1,
      sym_date,
  [153] = 1,
    ACTIONS(105), 1,
      sym__newline,
  [157] = 1,
    ACTIONS(117), 1,
      sym__newline,
  [161] = 1,
    ACTIONS(119), 1,
      ts_builtin_sym_end,
  [165] = 1,
    ACTIONS(109), 1,
      sym__newline,
  [169] = 1,
    ACTIONS(121), 1,
      sym__newline,
  [173] = 1,
    ACTIONS(123), 1,
      sym__newline,
  [177] = 1,
    ACTIONS(113), 1,
      sym__newline,
  [181] = 1,
    ACTIONS(125), 1,
      sym__newline,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 11,
  [SMALL_STATE(9)] = 22,
  [SMALL_STATE(10)] = 33,
  [SMALL_STATE(11)] = 44,
  [SMALL_STATE(12)] = 55,
  [SMALL_STATE(13)] = 66,
  [SMALL_STATE(14)] = 77,
  [SMALL_STATE(15)] = 88,
  [SMALL_STATE(16)] = 98,
  [SMALL_STATE(17)] = 108,
  [SMALL_STATE(18)] = 118,
  [SMALL_STATE(19)] = 128,
  [SMALL_STATE(20)] = 135,
  [SMALL_STATE(21)] = 142,
  [SMALL_STATE(22)] = 149,
  [SMALL_STATE(23)] = 153,
  [SMALL_STATE(24)] = 157,
  [SMALL_STATE(25)] = 161,
  [SMALL_STATE(26)] = 165,
  [SMALL_STATE(27)] = 169,
  [SMALL_STATE(28)] = 173,
  [SMALL_STATE(29)] = 177,
  [SMALL_STATE(30)] = 181,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_day, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_day, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_day, 2, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_day, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_day_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_day_repeat1, 2, 0, 0),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_day_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_day_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_date_header, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_date_header, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entry, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_date_header, 4, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_date_header, 4, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_date_header, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_date_header, 3, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entry, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_date_header, 5, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_date_header, 5, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry, 4, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entry, 4, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_line, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_line, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [119] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_hledger_timedot(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "hledger_timedot",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 1,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
