/* Automatically @generated by tree-sitter v0.25.5 (460118b4c82318b083b4d527c9c750426730f9c0) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 25
#define LARGE_STATE_COUNT 14
#define SYMBOL_COUNT 42
#define ALIAS_COUNT 0
#define TOKEN_COUNT 34
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_csv_line = 1,
  anon_sym_RULES = 2,
  anon_sym_skip = 3,
  anon_sym_fields = 4,
  anon_sym_separator = 5,
  anon_sym_newest_DASHfirst = 6,
  anon_sym_date_DASHformat = 7,
  anon_sym_decimal_DASHmark = 8,
  anon_sym_date = 9,
  anon_sym_date2 = 10,
  anon_sym_status = 11,
  anon_sym_code = 12,
  anon_sym_description = 13,
  anon_sym_comment = 14,
  anon_sym_account1 = 15,
  anon_sym_account2 = 16,
  anon_sym_amount = 17,
  anon_sym_amount_DASHin = 18,
  anon_sym_amount_DASHout = 19,
  anon_sym_currency = 20,
  anon_sym_balance = 21,
  anon_sym_balance1 = 22,
  anon_sym_balance2 = 23,
  anon_sym_include = 24,
  anon_sym_source = 25,
  anon_sym_end = 26,
  anon_sym_if = 27,
  anon_sym_AMP = 28,
  anon_sym_AMP_BANG = 29,
  aux_sym_indented_line_token1 = 30,
  sym__value = 31,
  aux_sym_comment_line_token1 = 32,
  sym__newline = 33,
  sym_source_file = 34,
  sym_rules_marker = 35,
  sym_directive = 36,
  sym_conditional_block = 37,
  sym_indented_line = 38,
  sym_comment_line = 39,
  aux_sym_source_file_repeat1 = 40,
  aux_sym_conditional_block_repeat1 = 41,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_csv_line] = "csv_line",
  [anon_sym_RULES] = "RULES",
  [anon_sym_skip] = "skip",
  [anon_sym_fields] = "fields",
  [anon_sym_separator] = "separator",
  [anon_sym_newest_DASHfirst] = "newest-first",
  [anon_sym_date_DASHformat] = "date-format",
  [anon_sym_decimal_DASHmark] = "decimal-mark",
  [anon_sym_date] = "date",
  [anon_sym_date2] = "date2",
  [anon_sym_status] = "status",
  [anon_sym_code] = "code",
  [anon_sym_description] = "description",
  [anon_sym_comment] = "comment",
  [anon_sym_account1] = "account1",
  [anon_sym_account2] = "account2",
  [anon_sym_amount] = "amount",
  [anon_sym_amount_DASHin] = "amount-in",
  [anon_sym_amount_DASHout] = "amount-out",
  [anon_sym_currency] = "currency",
  [anon_sym_balance] = "balance",
  [anon_sym_balance1] = "balance1",
  [anon_sym_balance2] = "balance2",
  [anon_sym_include] = "include",
  [anon_sym_source] = "source",
  [anon_sym_end] = "end",
  [anon_sym_if] = "if",
  [anon_sym_AMP] = "&",
  [anon_sym_AMP_BANG] = "&!",
  [aux_sym_indented_line_token1] = "indented_line_token1",
  [sym__value] = "_value",
  [aux_sym_comment_line_token1] = "comment_line_token1",
  [sym__newline] = "_newline",
  [sym_source_file] = "source_file",
  [sym_rules_marker] = "rules_marker",
  [sym_directive] = "directive",
  [sym_conditional_block] = "conditional_block",
  [sym_indented_line] = "indented_line",
  [sym_comment_line] = "comment_line",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_conditional_block_repeat1] = "conditional_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_csv_line] = sym_csv_line,
  [anon_sym_RULES] = anon_sym_RULES,
  [anon_sym_skip] = anon_sym_skip,
  [anon_sym_fields] = anon_sym_fields,
  [anon_sym_separator] = anon_sym_separator,
  [anon_sym_newest_DASHfirst] = anon_sym_newest_DASHfirst,
  [anon_sym_date_DASHformat] = anon_sym_date_DASHformat,
  [anon_sym_decimal_DASHmark] = anon_sym_decimal_DASHmark,
  [anon_sym_date] = anon_sym_date,
  [anon_sym_date2] = anon_sym_date2,
  [anon_sym_status] = anon_sym_status,
  [anon_sym_code] = anon_sym_code,
  [anon_sym_description] = anon_sym_description,
  [anon_sym_comment] = anon_sym_comment,
  [anon_sym_account1] = anon_sym_account1,
  [anon_sym_account2] = anon_sym_account2,
  [anon_sym_amount] = anon_sym_amount,
  [anon_sym_amount_DASHin] = anon_sym_amount_DASHin,
  [anon_sym_amount_DASHout] = anon_sym_amount_DASHout,
  [anon_sym_currency] = anon_sym_currency,
  [anon_sym_balance] = anon_sym_balance,
  [anon_sym_balance1] = anon_sym_balance1,
  [anon_sym_balance2] = anon_sym_balance2,
  [anon_sym_include] = anon_sym_include,
  [anon_sym_source] = anon_sym_source,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_AMP_BANG] = anon_sym_AMP_BANG,
  [aux_sym_indented_line_token1] = aux_sym_indented_line_token1,
  [sym__value] = sym__value,
  [aux_sym_comment_line_token1] = aux_sym_comment_line_token1,
  [sym__newline] = sym__newline,
  [sym_source_file] = sym_source_file,
  [sym_rules_marker] = sym_rules_marker,
  [sym_directive] = sym_directive,
  [sym_conditional_block] = sym_conditional_block,
  [sym_indented_line] = sym_indented_line,
  [sym_comment_line] = sym_comment_line,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_conditional_block_repeat1] = aux_sym_conditional_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_csv_line] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_RULES] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_skip] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fields] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_separator] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_newest_DASHfirst] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_date_DASHformat] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_decimal_DASHmark] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_date] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_date2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_status] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_code] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_description] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_comment] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_account1] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_account2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_amount] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_amount_DASHin] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_amount_DASHout] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_currency] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_balance] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_balance1] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_balance2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_include] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_source] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_indented_line_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_comment_line_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_rules_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_conditional_block] = {
    .visible = true,
    .named = true,
  },
  [sym_indented_line] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_conditional_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      ADVANCE_MAP(
        '\t', 145,
        '\n', 152,
        '\r', 8,
        ' ', 146,
        '&', 143,
        'R', 15,
        'a', 25,
        'b', 16,
        'c', 75,
        'd', 17,
        'e', 67,
        'f', 51,
        'i', 48,
        'n', 37,
        's', 38,
        '#', 151,
        ';', 151,
      );
      if (lookahead != 0) ADVANCE(116);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(152);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(152);
      if (lookahead == '\r') ADVANCE(148);
      if (lookahead == ' ') ADVANCE(147);
      if (lookahead != 0) ADVANCE(150);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(152);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(149);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(150);
      END_STATE();
    case 5:
      if (eof) ADVANCE(6);
      ADVANCE_MAP(
        '\n', 152,
        '\r', 8,
        ' ', 7,
        '&', 143,
        'R', 15,
        'a', 25,
        'b', 16,
        'c', 75,
        'd', 17,
        'e', 67,
        'f', 51,
        'i', 48,
        'n', 37,
        's', 38,
        '#', 151,
        ';', 151,
      );
      if (lookahead != 0) ADVANCE(116);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_csv_line);
      ADVANCE_MAP(
        '\n', 152,
        '\r', 8,
        ' ', 7,
        '&', 143,
        'R', 15,
        'a', 25,
        'b', 16,
        'c', 75,
        'd', 17,
        'e', 67,
        'f', 51,
        'i', 48,
        'n', 37,
        's', 38,
        '#', 151,
        ';', 151,
      );
      if (lookahead != 0) ADVANCE(116);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == '\n') ADVANCE(152);
      if (lookahead != 0) ADVANCE(116);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == '-') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == '-') ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == '1') ADVANCE(130);
      if (lookahead == '2') ADVANCE(131);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'E') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'L') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'S') ADVANCE(117);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'U') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'a') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'a') ADVANCE(105);
      if (lookahead == 'e') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'a') ADVANCE(106);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'a') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'a') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'a') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'a') ADVANCE(107);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'a') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'a') ADVANCE(102);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'c') ADVANCE(32);
      if (lookahead == 'm') ADVANCE(76);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'c') ADVANCE(115);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'c') ADVANCE(53);
      if (lookahead == 's') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'c') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'c') ADVANCE(92);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'c') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'c') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'c') ADVANCE(80);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'd') ADVANCE(141);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'd') ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'd') ADVANCE(39);
      if (lookahead == 'm') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'd') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'e') ADVANCE(114);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'e') ADVANCE(82);
      if (lookahead == 'k') ADVANCE(52);
      if (lookahead == 'o') ADVANCE(109);
      if (lookahead == 't') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'e') ADVANCE(127);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'e') ADVANCE(124);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'e') ADVANCE(95);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'e') ADVANCE(140);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'e') ADVANCE(136);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'e') ADVANCE(139);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'e') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'e') ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'e') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'f') ADVANCE(142);
      if (lookahead == 'n') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'f') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'f') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'i') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'i') ADVANCE(81);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'i') ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'i') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'i') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'i') ADVANCE(68);
      if (lookahead == 'o') ADVANCE(112);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'i') ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'k') ADVANCE(123);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'l') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'l') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'l') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'l') ADVANCE(110);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'm') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'm') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'm') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'm') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'n') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'n') ADVANCE(133);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'n') ADVANCE(128);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'n') ADVANCE(97);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'n') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'n') ADVANCE(99);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'n') ADVANCE(100);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'n') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'o') ADVANCE(35);
      if (lookahead == 'u') ADVANCE(86);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'o') ADVANCE(108);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'o') ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'o') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'o') ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'o') ADVANCE(113);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'p') ADVANCE(118);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'p') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'p') ADVANCE(104);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'r') ADVANCE(120);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'r') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'r') ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'r') ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'r') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'r') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'r') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'r') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'r') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 's') ADVANCE(119);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 's') ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 's') ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 's') ADVANCE(103);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 't') ADVANCE(132);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 't') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 't') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 't') ADVANCE(129);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 't') ADVANCE(134);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 't') ADVANCE(122);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 't') ADVANCE(121);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 't') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 't') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 't') ADVANCE(111);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 't') ADVANCE(79);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'u') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'u') ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'u') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'u') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'u') ADVANCE(101);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'u') ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'w') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead == 'y') ADVANCE(135);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_csv_line);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_RULES);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_skip);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_fields);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_separator);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(anon_sym_newest_DASHfirst);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(anon_sym_date_DASHformat);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_decimal_DASHmark);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(anon_sym_date);
      if (lookahead == '-') ADVANCE(49);
      if (lookahead == '2') ADVANCE(125);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(anon_sym_date2);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_status);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(anon_sym_code);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(anon_sym_description);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(anon_sym_comment);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(anon_sym_account1);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(anon_sym_account2);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(anon_sym_amount);
      if (lookahead == '-') ADVANCE(56);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(anon_sym_amount_DASHin);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(anon_sym_amount_DASHout);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(anon_sym_currency);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(anon_sym_balance);
      if (lookahead == '1') ADVANCE(137);
      if (lookahead == '2') ADVANCE(138);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(anon_sym_balance1);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(anon_sym_balance2);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(anon_sym_include);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(anon_sym_source);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(anon_sym_AMP);
      if (lookahead == '!') ADVANCE(144);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(anon_sym_AMP_BANG);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(aux_sym_indented_line_token1);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(aux_sym_indented_line_token1);
      if (lookahead == '\t') ADVANCE(145);
      if (lookahead == ' ') ADVANCE(146);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym__value);
      if (lookahead == '\n') ADVANCE(152);
      if (lookahead == '\r') ADVANCE(148);
      if (lookahead == ' ') ADVANCE(147);
      if (lookahead != 0) ADVANCE(150);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym__value);
      if (lookahead == '\n') ADVANCE(152);
      if (lookahead != 0) ADVANCE(150);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym__value);
      if (lookahead == ' ') ADVANCE(149);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(150);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym__value);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(150);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(aux_sym_comment_line_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(151);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 5},
  [2] = {.lex_state = 5},
  [3] = {.lex_state = 5},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 5},
  [11] = {.lex_state = 5},
  [12] = {.lex_state = 5},
  [13] = {.lex_state = 5},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 4},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_csv_line] = ACTIONS(1),
    [anon_sym_RULES] = ACTIONS(1),
    [anon_sym_skip] = ACTIONS(1),
    [anon_sym_fields] = ACTIONS(1),
    [anon_sym_separator] = ACTIONS(1),
    [anon_sym_newest_DASHfirst] = ACTIONS(1),
    [anon_sym_date_DASHformat] = ACTIONS(1),
    [anon_sym_decimal_DASHmark] = ACTIONS(1),
    [anon_sym_date] = ACTIONS(1),
    [anon_sym_date2] = ACTIONS(1),
    [anon_sym_status] = ACTIONS(1),
    [anon_sym_code] = ACTIONS(1),
    [anon_sym_description] = ACTIONS(1),
    [anon_sym_comment] = ACTIONS(1),
    [anon_sym_account1] = ACTIONS(1),
    [anon_sym_account2] = ACTIONS(1),
    [anon_sym_amount] = ACTIONS(1),
    [anon_sym_amount_DASHin] = ACTIONS(1),
    [anon_sym_amount_DASHout] = ACTIONS(1),
    [anon_sym_currency] = ACTIONS(1),
    [anon_sym_balance] = ACTIONS(1),
    [anon_sym_balance1] = ACTIONS(1),
    [anon_sym_balance2] = ACTIONS(1),
    [anon_sym_include] = ACTIONS(1),
    [anon_sym_source] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_AMP_BANG] = ACTIONS(1),
    [aux_sym_indented_line_token1] = ACTIONS(1),
    [aux_sym_comment_line_token1] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(20),
    [sym_rules_marker] = STATE(2),
    [sym_directive] = STATE(2),
    [sym_conditional_block] = STATE(2),
    [sym_comment_line] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_csv_line] = ACTIONS(5),
    [anon_sym_RULES] = ACTIONS(7),
    [anon_sym_skip] = ACTIONS(9),
    [anon_sym_fields] = ACTIONS(11),
    [anon_sym_separator] = ACTIONS(11),
    [anon_sym_newest_DASHfirst] = ACTIONS(9),
    [anon_sym_date_DASHformat] = ACTIONS(11),
    [anon_sym_decimal_DASHmark] = ACTIONS(11),
    [anon_sym_date] = ACTIONS(11),
    [anon_sym_date2] = ACTIONS(11),
    [anon_sym_status] = ACTIONS(11),
    [anon_sym_code] = ACTIONS(11),
    [anon_sym_description] = ACTIONS(11),
    [anon_sym_comment] = ACTIONS(11),
    [anon_sym_account1] = ACTIONS(11),
    [anon_sym_account2] = ACTIONS(11),
    [anon_sym_amount] = ACTIONS(11),
    [anon_sym_amount_DASHin] = ACTIONS(11),
    [anon_sym_amount_DASHout] = ACTIONS(11),
    [anon_sym_currency] = ACTIONS(11),
    [anon_sym_balance] = ACTIONS(11),
    [anon_sym_balance1] = ACTIONS(11),
    [anon_sym_balance2] = ACTIONS(11),
    [anon_sym_include] = ACTIONS(11),
    [anon_sym_source] = ACTIONS(11),
    [anon_sym_end] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_AMP] = ACTIONS(15),
    [anon_sym_AMP_BANG] = ACTIONS(15),
    [aux_sym_comment_line_token1] = ACTIONS(17),
    [sym__newline] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym_rules_marker] = STATE(3),
    [sym_directive] = STATE(3),
    [sym_conditional_block] = STATE(3),
    [sym_comment_line] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(19),
    [sym_csv_line] = ACTIONS(21),
    [anon_sym_RULES] = ACTIONS(7),
    [anon_sym_skip] = ACTIONS(9),
    [anon_sym_fields] = ACTIONS(11),
    [anon_sym_separator] = ACTIONS(11),
    [anon_sym_newest_DASHfirst] = ACTIONS(9),
    [anon_sym_date_DASHformat] = ACTIONS(11),
    [anon_sym_decimal_DASHmark] = ACTIONS(11),
    [anon_sym_date] = ACTIONS(11),
    [anon_sym_date2] = ACTIONS(11),
    [anon_sym_status] = ACTIONS(11),
    [anon_sym_code] = ACTIONS(11),
    [anon_sym_description] = ACTIONS(11),
    [anon_sym_comment] = ACTIONS(11),
    [anon_sym_account1] = ACTIONS(11),
    [anon_sym_account2] = ACTIONS(11),
    [anon_sym_amount] = ACTIONS(11),
    [anon_sym_amount_DASHin] = ACTIONS(11),
    [anon_sym_amount_DASHout] = ACTIONS(11),
    [anon_sym_currency] = ACTIONS(11),
    [anon_sym_balance] = ACTIONS(11),
    [anon_sym_balance1] = ACTIONS(11),
    [anon_sym_balance2] = ACTIONS(11),
    [anon_sym_include] = ACTIONS(11),
    [anon_sym_source] = ACTIONS(11),
    [anon_sym_end] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_AMP] = ACTIONS(15),
    [anon_sym_AMP_BANG] = ACTIONS(15),
    [aux_sym_comment_line_token1] = ACTIONS(17),
    [sym__newline] = ACTIONS(21),
  },
  [STATE(3)] = {
    [sym_rules_marker] = STATE(3),
    [sym_directive] = STATE(3),
    [sym_conditional_block] = STATE(3),
    [sym_comment_line] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_csv_line] = ACTIONS(25),
    [anon_sym_RULES] = ACTIONS(28),
    [anon_sym_skip] = ACTIONS(31),
    [anon_sym_fields] = ACTIONS(34),
    [anon_sym_separator] = ACTIONS(34),
    [anon_sym_newest_DASHfirst] = ACTIONS(31),
    [anon_sym_date_DASHformat] = ACTIONS(34),
    [anon_sym_decimal_DASHmark] = ACTIONS(34),
    [anon_sym_date] = ACTIONS(34),
    [anon_sym_date2] = ACTIONS(34),
    [anon_sym_status] = ACTIONS(34),
    [anon_sym_code] = ACTIONS(34),
    [anon_sym_description] = ACTIONS(34),
    [anon_sym_comment] = ACTIONS(34),
    [anon_sym_account1] = ACTIONS(34),
    [anon_sym_account2] = ACTIONS(34),
    [anon_sym_amount] = ACTIONS(34),
    [anon_sym_amount_DASHin] = ACTIONS(34),
    [anon_sym_amount_DASHout] = ACTIONS(34),
    [anon_sym_currency] = ACTIONS(34),
    [anon_sym_balance] = ACTIONS(34),
    [anon_sym_balance1] = ACTIONS(34),
    [anon_sym_balance2] = ACTIONS(34),
    [anon_sym_include] = ACTIONS(34),
    [anon_sym_source] = ACTIONS(34),
    [anon_sym_end] = ACTIONS(37),
    [anon_sym_if] = ACTIONS(40),
    [anon_sym_AMP] = ACTIONS(40),
    [anon_sym_AMP_BANG] = ACTIONS(40),
    [aux_sym_comment_line_token1] = ACTIONS(43),
    [sym__newline] = ACTIONS(25),
  },
  [STATE(4)] = {
    [sym_indented_line] = STATE(7),
    [aux_sym_conditional_block_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(46),
    [sym_csv_line] = ACTIONS(48),
    [anon_sym_RULES] = ACTIONS(48),
    [anon_sym_skip] = ACTIONS(48),
    [anon_sym_fields] = ACTIONS(48),
    [anon_sym_separator] = ACTIONS(48),
    [anon_sym_newest_DASHfirst] = ACTIONS(48),
    [anon_sym_date_DASHformat] = ACTIONS(48),
    [anon_sym_decimal_DASHmark] = ACTIONS(48),
    [anon_sym_date] = ACTIONS(48),
    [anon_sym_date2] = ACTIONS(48),
    [anon_sym_status] = ACTIONS(48),
    [anon_sym_code] = ACTIONS(48),
    [anon_sym_description] = ACTIONS(48),
    [anon_sym_comment] = ACTIONS(48),
    [anon_sym_account1] = ACTIONS(48),
    [anon_sym_account2] = ACTIONS(48),
    [anon_sym_amount] = ACTIONS(48),
    [anon_sym_amount_DASHin] = ACTIONS(48),
    [anon_sym_amount_DASHout] = ACTIONS(48),
    [anon_sym_currency] = ACTIONS(48),
    [anon_sym_balance] = ACTIONS(48),
    [anon_sym_balance1] = ACTIONS(48),
    [anon_sym_balance2] = ACTIONS(48),
    [anon_sym_include] = ACTIONS(48),
    [anon_sym_source] = ACTIONS(48),
    [anon_sym_end] = ACTIONS(48),
    [anon_sym_if] = ACTIONS(48),
    [anon_sym_AMP] = ACTIONS(48),
    [anon_sym_AMP_BANG] = ACTIONS(48),
    [aux_sym_indented_line_token1] = ACTIONS(50),
    [aux_sym_comment_line_token1] = ACTIONS(48),
    [sym__newline] = ACTIONS(48),
  },
  [STATE(5)] = {
    [sym_indented_line] = STATE(6),
    [aux_sym_conditional_block_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(52),
    [sym_csv_line] = ACTIONS(54),
    [anon_sym_RULES] = ACTIONS(54),
    [anon_sym_skip] = ACTIONS(54),
    [anon_sym_fields] = ACTIONS(54),
    [anon_sym_separator] = ACTIONS(54),
    [anon_sym_newest_DASHfirst] = ACTIONS(54),
    [anon_sym_date_DASHformat] = ACTIONS(54),
    [anon_sym_decimal_DASHmark] = ACTIONS(54),
    [anon_sym_date] = ACTIONS(54),
    [anon_sym_date2] = ACTIONS(54),
    [anon_sym_status] = ACTIONS(54),
    [anon_sym_code] = ACTIONS(54),
    [anon_sym_description] = ACTIONS(54),
    [anon_sym_comment] = ACTIONS(54),
    [anon_sym_account1] = ACTIONS(54),
    [anon_sym_account2] = ACTIONS(54),
    [anon_sym_amount] = ACTIONS(54),
    [anon_sym_amount_DASHin] = ACTIONS(54),
    [anon_sym_amount_DASHout] = ACTIONS(54),
    [anon_sym_currency] = ACTIONS(54),
    [anon_sym_balance] = ACTIONS(54),
    [anon_sym_balance1] = ACTIONS(54),
    [anon_sym_balance2] = ACTIONS(54),
    [anon_sym_include] = ACTIONS(54),
    [anon_sym_source] = ACTIONS(54),
    [anon_sym_end] = ACTIONS(54),
    [anon_sym_if] = ACTIONS(54),
    [anon_sym_AMP] = ACTIONS(54),
    [anon_sym_AMP_BANG] = ACTIONS(54),
    [aux_sym_indented_line_token1] = ACTIONS(50),
    [aux_sym_comment_line_token1] = ACTIONS(54),
    [sym__newline] = ACTIONS(54),
  },
  [STATE(6)] = {
    [sym_indented_line] = STATE(8),
    [aux_sym_conditional_block_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(46),
    [sym_csv_line] = ACTIONS(48),
    [anon_sym_RULES] = ACTIONS(48),
    [anon_sym_skip] = ACTIONS(48),
    [anon_sym_fields] = ACTIONS(48),
    [anon_sym_separator] = ACTIONS(48),
    [anon_sym_newest_DASHfirst] = ACTIONS(48),
    [anon_sym_date_DASHformat] = ACTIONS(48),
    [anon_sym_decimal_DASHmark] = ACTIONS(48),
    [anon_sym_date] = ACTIONS(48),
    [anon_sym_date2] = ACTIONS(48),
    [anon_sym_status] = ACTIONS(48),
    [anon_sym_code] = ACTIONS(48),
    [anon_sym_description] = ACTIONS(48),
    [anon_sym_comment] = ACTIONS(48),
    [anon_sym_account1] = ACTIONS(48),
    [anon_sym_account2] = ACTIONS(48),
    [anon_sym_amount] = ACTIONS(48),
    [anon_sym_amount_DASHin] = ACTIONS(48),
    [anon_sym_amount_DASHout] = ACTIONS(48),
    [anon_sym_currency] = ACTIONS(48),
    [anon_sym_balance] = ACTIONS(48),
    [anon_sym_balance1] = ACTIONS(48),
    [anon_sym_balance2] = ACTIONS(48),
    [anon_sym_include] = ACTIONS(48),
    [anon_sym_source] = ACTIONS(48),
    [anon_sym_end] = ACTIONS(48),
    [anon_sym_if] = ACTIONS(48),
    [anon_sym_AMP] = ACTIONS(48),
    [anon_sym_AMP_BANG] = ACTIONS(48),
    [aux_sym_indented_line_token1] = ACTIONS(50),
    [aux_sym_comment_line_token1] = ACTIONS(48),
    [sym__newline] = ACTIONS(48),
  },
  [STATE(7)] = {
    [sym_indented_line] = STATE(8),
    [aux_sym_conditional_block_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(56),
    [sym_csv_line] = ACTIONS(58),
    [anon_sym_RULES] = ACTIONS(58),
    [anon_sym_skip] = ACTIONS(58),
    [anon_sym_fields] = ACTIONS(58),
    [anon_sym_separator] = ACTIONS(58),
    [anon_sym_newest_DASHfirst] = ACTIONS(58),
    [anon_sym_date_DASHformat] = ACTIONS(58),
    [anon_sym_decimal_DASHmark] = ACTIONS(58),
    [anon_sym_date] = ACTIONS(58),
    [anon_sym_date2] = ACTIONS(58),
    [anon_sym_status] = ACTIONS(58),
    [anon_sym_code] = ACTIONS(58),
    [anon_sym_description] = ACTIONS(58),
    [anon_sym_comment] = ACTIONS(58),
    [anon_sym_account1] = ACTIONS(58),
    [anon_sym_account2] = ACTIONS(58),
    [anon_sym_amount] = ACTIONS(58),
    [anon_sym_amount_DASHin] = ACTIONS(58),
    [anon_sym_amount_DASHout] = ACTIONS(58),
    [anon_sym_currency] = ACTIONS(58),
    [anon_sym_balance] = ACTIONS(58),
    [anon_sym_balance1] = ACTIONS(58),
    [anon_sym_balance2] = ACTIONS(58),
    [anon_sym_include] = ACTIONS(58),
    [anon_sym_source] = ACTIONS(58),
    [anon_sym_end] = ACTIONS(58),
    [anon_sym_if] = ACTIONS(58),
    [anon_sym_AMP] = ACTIONS(58),
    [anon_sym_AMP_BANG] = ACTIONS(58),
    [aux_sym_indented_line_token1] = ACTIONS(50),
    [aux_sym_comment_line_token1] = ACTIONS(58),
    [sym__newline] = ACTIONS(58),
  },
  [STATE(8)] = {
    [sym_indented_line] = STATE(8),
    [aux_sym_conditional_block_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(60),
    [sym_csv_line] = ACTIONS(62),
    [anon_sym_RULES] = ACTIONS(62),
    [anon_sym_skip] = ACTIONS(62),
    [anon_sym_fields] = ACTIONS(62),
    [anon_sym_separator] = ACTIONS(62),
    [anon_sym_newest_DASHfirst] = ACTIONS(62),
    [anon_sym_date_DASHformat] = ACTIONS(62),
    [anon_sym_decimal_DASHmark] = ACTIONS(62),
    [anon_sym_date] = ACTIONS(62),
    [anon_sym_date2] = ACTIONS(62),
    [anon_sym_status] = ACTIONS(62),
    [anon_sym_code] = ACTIONS(62),
    [anon_sym_description] = ACTIONS(62),
    [anon_sym_comment] = ACTIONS(62),
    [anon_sym_account1] = ACTIONS(62),
    [anon_sym_account2] = ACTIONS(62),
    [anon_sym_amount] = ACTIONS(62),
    [anon_sym_amount_DASHin] = ACTIONS(62),
    [anon_sym_amount_DASHout] = ACTIONS(62),
    [anon_sym_currency] = ACTIONS(62),
    [anon_sym_balance] = ACTIONS(62),
    [anon_sym_balance1] = ACTIONS(62),
    [anon_sym_balance2] = ACTIONS(62),
    [anon_sym_include] = ACTIONS(62),
    [anon_sym_source] = ACTIONS(62),
    [anon_sym_end] = ACTIONS(62),
    [anon_sym_if] = ACTIONS(62),
    [anon_sym_AMP] = ACTIONS(62),
    [anon_sym_AMP_BANG] = ACTIONS(62),
    [aux_sym_indented_line_token1] = ACTIONS(64),
    [aux_sym_comment_line_token1] = ACTIONS(62),
    [sym__newline] = ACTIONS(62),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(67),
    [sym_csv_line] = ACTIONS(69),
    [anon_sym_RULES] = ACTIONS(69),
    [anon_sym_skip] = ACTIONS(69),
    [anon_sym_fields] = ACTIONS(69),
    [anon_sym_separator] = ACTIONS(69),
    [anon_sym_newest_DASHfirst] = ACTIONS(69),
    [anon_sym_date_DASHformat] = ACTIONS(69),
    [anon_sym_decimal_DASHmark] = ACTIONS(69),
    [anon_sym_date] = ACTIONS(69),
    [anon_sym_date2] = ACTIONS(69),
    [anon_sym_status] = ACTIONS(69),
    [anon_sym_code] = ACTIONS(69),
    [anon_sym_description] = ACTIONS(69),
    [anon_sym_comment] = ACTIONS(69),
    [anon_sym_account1] = ACTIONS(69),
    [anon_sym_account2] = ACTIONS(69),
    [anon_sym_amount] = ACTIONS(69),
    [anon_sym_amount_DASHin] = ACTIONS(69),
    [anon_sym_amount_DASHout] = ACTIONS(69),
    [anon_sym_currency] = ACTIONS(69),
    [anon_sym_balance] = ACTIONS(69),
    [anon_sym_balance1] = ACTIONS(69),
    [anon_sym_balance2] = ACTIONS(69),
    [anon_sym_include] = ACTIONS(69),
    [anon_sym_source] = ACTIONS(69),
    [anon_sym_end] = ACTIONS(69),
    [anon_sym_if] = ACTIONS(69),
    [anon_sym_AMP] = ACTIONS(69),
    [anon_sym_AMP_BANG] = ACTIONS(69),
    [aux_sym_indented_line_token1] = ACTIONS(69),
    [aux_sym_comment_line_token1] = ACTIONS(69),
    [sym__newline] = ACTIONS(69),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(71),
    [sym_csv_line] = ACTIONS(73),
    [anon_sym_RULES] = ACTIONS(73),
    [anon_sym_skip] = ACTIONS(73),
    [anon_sym_fields] = ACTIONS(73),
    [anon_sym_separator] = ACTIONS(73),
    [anon_sym_newest_DASHfirst] = ACTIONS(73),
    [anon_sym_date_DASHformat] = ACTIONS(73),
    [anon_sym_decimal_DASHmark] = ACTIONS(73),
    [anon_sym_date] = ACTIONS(73),
    [anon_sym_date2] = ACTIONS(73),
    [anon_sym_status] = ACTIONS(73),
    [anon_sym_code] = ACTIONS(73),
    [anon_sym_description] = ACTIONS(73),
    [anon_sym_comment] = ACTIONS(73),
    [anon_sym_account1] = ACTIONS(73),
    [anon_sym_account2] = ACTIONS(73),
    [anon_sym_amount] = ACTIONS(73),
    [anon_sym_amount_DASHin] = ACTIONS(73),
    [anon_sym_amount_DASHout] = ACTIONS(73),
    [anon_sym_currency] = ACTIONS(73),
    [anon_sym_balance] = ACTIONS(73),
    [anon_sym_balance1] = ACTIONS(73),
    [anon_sym_balance2] = ACTIONS(73),
    [anon_sym_include] = ACTIONS(73),
    [anon_sym_source] = ACTIONS(73),
    [anon_sym_end] = ACTIONS(73),
    [anon_sym_if] = ACTIONS(73),
    [anon_sym_AMP] = ACTIONS(73),
    [anon_sym_AMP_BANG] = ACTIONS(73),
    [aux_sym_comment_line_token1] = ACTIONS(73),
    [sym__newline] = ACTIONS(73),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(75),
    [sym_csv_line] = ACTIONS(77),
    [anon_sym_RULES] = ACTIONS(77),
    [anon_sym_skip] = ACTIONS(77),
    [anon_sym_fields] = ACTIONS(77),
    [anon_sym_separator] = ACTIONS(77),
    [anon_sym_newest_DASHfirst] = ACTIONS(77),
    [anon_sym_date_DASHformat] = ACTIONS(77),
    [anon_sym_decimal_DASHmark] = ACTIONS(77),
    [anon_sym_date] = ACTIONS(77),
    [anon_sym_date2] = ACTIONS(77),
    [anon_sym_status] = ACTIONS(77),
    [anon_sym_code] = ACTIONS(77),
    [anon_sym_description] = ACTIONS(77),
    [anon_sym_comment] = ACTIONS(77),
    [anon_sym_account1] = ACTIONS(77),
    [anon_sym_account2] = ACTIONS(77),
    [anon_sym_amount] = ACTIONS(77),
    [anon_sym_amount_DASHin] = ACTIONS(77),
    [anon_sym_amount_DASHout] = ACTIONS(77),
    [anon_sym_currency] = ACTIONS(77),
    [anon_sym_balance] = ACTIONS(77),
    [anon_sym_balance1] = ACTIONS(77),
    [anon_sym_balance2] = ACTIONS(77),
    [anon_sym_include] = ACTIONS(77),
    [anon_sym_source] = ACTIONS(77),
    [anon_sym_end] = ACTIONS(77),
    [anon_sym_if] = ACTIONS(77),
    [anon_sym_AMP] = ACTIONS(77),
    [anon_sym_AMP_BANG] = ACTIONS(77),
    [aux_sym_comment_line_token1] = ACTIONS(77),
    [sym__newline] = ACTIONS(77),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(79),
    [sym_csv_line] = ACTIONS(81),
    [anon_sym_RULES] = ACTIONS(81),
    [anon_sym_skip] = ACTIONS(81),
    [anon_sym_fields] = ACTIONS(81),
    [anon_sym_separator] = ACTIONS(81),
    [anon_sym_newest_DASHfirst] = ACTIONS(81),
    [anon_sym_date_DASHformat] = ACTIONS(81),
    [anon_sym_decimal_DASHmark] = ACTIONS(81),
    [anon_sym_date] = ACTIONS(81),
    [anon_sym_date2] = ACTIONS(81),
    [anon_sym_status] = ACTIONS(81),
    [anon_sym_code] = ACTIONS(81),
    [anon_sym_description] = ACTIONS(81),
    [anon_sym_comment] = ACTIONS(81),
    [anon_sym_account1] = ACTIONS(81),
    [anon_sym_account2] = ACTIONS(81),
    [anon_sym_amount] = ACTIONS(81),
    [anon_sym_amount_DASHin] = ACTIONS(81),
    [anon_sym_amount_DASHout] = ACTIONS(81),
    [anon_sym_currency] = ACTIONS(81),
    [anon_sym_balance] = ACTIONS(81),
    [anon_sym_balance1] = ACTIONS(81),
    [anon_sym_balance2] = ACTIONS(81),
    [anon_sym_include] = ACTIONS(81),
    [anon_sym_source] = ACTIONS(81),
    [anon_sym_end] = ACTIONS(81),
    [anon_sym_if] = ACTIONS(81),
    [anon_sym_AMP] = ACTIONS(81),
    [anon_sym_AMP_BANG] = ACTIONS(81),
    [aux_sym_comment_line_token1] = ACTIONS(81),
    [sym__newline] = ACTIONS(81),
  },
  [STATE(13)] = {
    [ts_builtin_sym_end] = ACTIONS(83),
    [sym_csv_line] = ACTIONS(85),
    [anon_sym_RULES] = ACTIONS(85),
    [anon_sym_skip] = ACTIONS(85),
    [anon_sym_fields] = ACTIONS(85),
    [anon_sym_separator] = ACTIONS(85),
    [anon_sym_newest_DASHfirst] = ACTIONS(85),
    [anon_sym_date_DASHformat] = ACTIONS(85),
    [anon_sym_decimal_DASHmark] = ACTIONS(85),
    [anon_sym_date] = ACTIONS(85),
    [anon_sym_date2] = ACTIONS(85),
    [anon_sym_status] = ACTIONS(85),
    [anon_sym_code] = ACTIONS(85),
    [anon_sym_description] = ACTIONS(85),
    [anon_sym_comment] = ACTIONS(85),
    [anon_sym_account1] = ACTIONS(85),
    [anon_sym_account2] = ACTIONS(85),
    [anon_sym_amount] = ACTIONS(85),
    [anon_sym_amount_DASHin] = ACTIONS(85),
    [anon_sym_amount_DASHout] = ACTIONS(85),
    [anon_sym_currency] = ACTIONS(85),
    [anon_sym_balance] = ACTIONS(85),
    [anon_sym_balance1] = ACTIONS(85),
    [anon_sym_balance2] = ACTIONS(85),
    [anon_sym_include] = ACTIONS(85),
    [anon_sym_source] = ACTIONS(85),
    [anon_sym_end] = ACTIONS(85),
    [anon_sym_if] = ACTIONS(85),
    [anon_sym_AMP] = ACTIONS(85),
    [anon_sym_AMP_BANG] = ACTIONS(85),
    [aux_sym_comment_line_token1] = ACTIONS(85),
    [sym__newline] = ACTIONS(85),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(87), 1,
      sym__value,
    ACTIONS(89), 1,
      sym__newline,
  [7] = 2,
    ACTIONS(91), 1,
      sym__value,
    ACTIONS(93), 1,
      sym__newline,
  [14] = 1,
    ACTIONS(95), 1,
      sym__newline,
  [18] = 1,
    ACTIONS(97), 1,
      sym__value,
  [22] = 1,
    ACTIONS(99), 1,
      sym__newline,
  [26] = 1,
    ACTIONS(101), 1,
      sym__newline,
  [30] = 1,
    ACTIONS(103), 1,
      ts_builtin_sym_end,
  [34] = 1,
    ACTIONS(105), 1,
      sym__newline,
  [38] = 1,
    ACTIONS(107), 1,
      sym__value,
  [42] = 1,
    ACTIONS(109), 1,
      sym__newline,
  [46] = 1,
    ACTIONS(111), 1,
      sym__newline,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(14)] = 0,
  [SMALL_STATE(15)] = 7,
  [SMALL_STATE(16)] = 14,
  [SMALL_STATE(17)] = 18,
  [SMALL_STATE(18)] = 22,
  [SMALL_STATE(19)] = 26,
  [SMALL_STATE(20)] = 30,
  [SMALL_STATE(21)] = 34,
  [SMALL_STATE(22)] = 38,
  [SMALL_STATE(23)] = 42,
  [SMALL_STATE(24)] = 46,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional_block, 3, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conditional_block, 3, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional_block, 2, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conditional_block, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional_block, 4, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conditional_block, 4, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_conditional_block_repeat1, 2, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_conditional_block_repeat1, 2, 0, 0),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_conditional_block_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_indented_line, 3, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_indented_line, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rules_marker, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rules_marker, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_line, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_line, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [103] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_hledger_csv(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "hledger_csv",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 1,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
