/* Automatically @generated by tree-sitter v0.25.5 (460118b4c82318b083b4d527c9c750426730f9c0) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 23
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 13
#define ALIAS_COUNT 0
#define TOKEN_COUNT 8
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_i = 1,
  anon_sym_o = 2,
  sym_datetime = 3,
  sym_content = 4,
  sym_comment = 5,
  aux_sym_comment_line_token1 = 6,
  sym__newline = 7,
  sym_source_file = 8,
  sym_clock_in = 9,
  sym_clock_out = 10,
  sym_comment_line = 11,
  aux_sym_source_file_repeat1 = 12,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_i] = "i",
  [anon_sym_o] = "o",
  [sym_datetime] = "datetime",
  [sym_content] = "content",
  [sym_comment] = "comment",
  [aux_sym_comment_line_token1] = "comment_line_token1",
  [sym__newline] = "_newline",
  [sym_source_file] = "source_file",
  [sym_clock_in] = "clock_in",
  [sym_clock_out] = "clock_out",
  [sym_comment_line] = "comment_line",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_i] = anon_sym_i,
  [anon_sym_o] = anon_sym_o,
  [sym_datetime] = sym_datetime,
  [sym_content] = sym_content,
  [sym_comment] = sym_comment,
  [aux_sym_comment_line_token1] = aux_sym_comment_line_token1,
  [sym__newline] = sym__newline,
  [sym_source_file] = sym_source_file,
  [sym_clock_in] = sym_clock_in,
  [sym_clock_out] = sym_clock_out,
  [sym_comment_line] = sym_comment_line,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_i] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_o] = {
    .visible = true,
    .named = false,
  },
  [sym_datetime] = {
    .visible = true,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_comment_line_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_clock_in] = {
    .visible = true,
    .named = true,
  },
  [sym_clock_out] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(22);
      if (lookahead == '\n') ADVANCE(32);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') SKIP(0);
      if (lookahead == '#') ADVANCE(31);
      if (lookahead == ';') ADVANCE(30);
      if (lookahead == 'i') ADVANCE(23);
      if (lookahead == 'o') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(32);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(32);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') SKIP(2);
      if (lookahead == ';') ADVANCE(30);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(32);
      if (lookahead == '\r') ADVANCE(28);
      if (lookahead == ' ') ADVANCE(27);
      if (lookahead == ';') ADVANCE(30);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 7:
      if (lookahead == ':') ADVANCE(18);
      END_STATE();
    case 8:
      if (lookahead == '-' ||
          lookahead == '/') ADVANCE(12);
      END_STATE();
    case 9:
      if (lookahead == '-' ||
          lookahead == '/') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == '-' ||
          lookahead == '/') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 21:
      if (eof) ADVANCE(22);
      if (lookahead == '\n') ADVANCE(32);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') SKIP(21);
      if (lookahead == 'i') ADVANCE(23);
      if (lookahead == 'o') ADVANCE(24);
      if (lookahead == '#' ||
          lookahead == ';') ADVANCE(31);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_i);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_o);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_datetime);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_datetime);
      if (lookahead == ':') ADVANCE(19);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == '\n') ADVANCE(32);
      if (lookahead == '\r') ADVANCE(28);
      if (lookahead == ' ') ADVANCE(27);
      if (lookahead == ';') ADVANCE(30);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == '\n') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != ';') ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_content);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_comment_line_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 21},
  [2] = {.lex_state = 21},
  [3] = {.lex_state = 21},
  [4] = {.lex_state = 21},
  [5] = {.lex_state = 21},
  [6] = {.lex_state = 21},
  [7] = {.lex_state = 21},
  [8] = {.lex_state = 21},
  [9] = {.lex_state = 21},
  [10] = {.lex_state = 21},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_i] = ACTIONS(1),
    [anon_sym_o] = ACTIONS(1),
    [sym_datetime] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [aux_sym_comment_line_token1] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(16),
    [sym_clock_in] = STATE(2),
    [sym_clock_out] = STATE(2),
    [sym_comment_line] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_i] = ACTIONS(5),
    [anon_sym_o] = ACTIONS(7),
    [aux_sym_comment_line_token1] = ACTIONS(9),
    [sym__newline] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym_clock_in] = STATE(3),
    [sym_clock_out] = STATE(3),
    [sym_comment_line] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(13),
    [anon_sym_i] = ACTIONS(5),
    [anon_sym_o] = ACTIONS(7),
    [aux_sym_comment_line_token1] = ACTIONS(9),
    [sym__newline] = ACTIONS(15),
  },
  [STATE(3)] = {
    [sym_clock_in] = STATE(3),
    [sym_clock_out] = STATE(3),
    [sym_comment_line] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(17),
    [anon_sym_i] = ACTIONS(19),
    [anon_sym_o] = ACTIONS(22),
    [aux_sym_comment_line_token1] = ACTIONS(25),
    [sym__newline] = ACTIONS(28),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(31), 5,
      ts_builtin_sym_end,
      anon_sym_i,
      anon_sym_o,
      aux_sym_comment_line_token1,
      sym__newline,
  [8] = 1,
    ACTIONS(33), 5,
      ts_builtin_sym_end,
      anon_sym_i,
      anon_sym_o,
      aux_sym_comment_line_token1,
      sym__newline,
  [16] = 1,
    ACTIONS(35), 5,
      ts_builtin_sym_end,
      anon_sym_i,
      anon_sym_o,
      aux_sym_comment_line_token1,
      sym__newline,
  [24] = 1,
    ACTIONS(37), 5,
      ts_builtin_sym_end,
      anon_sym_i,
      anon_sym_o,
      aux_sym_comment_line_token1,
      sym__newline,
  [32] = 1,
    ACTIONS(39), 5,
      ts_builtin_sym_end,
      anon_sym_i,
      anon_sym_o,
      aux_sym_comment_line_token1,
      sym__newline,
  [40] = 1,
    ACTIONS(41), 5,
      ts_builtin_sym_end,
      anon_sym_i,
      anon_sym_o,
      aux_sym_comment_line_token1,
      sym__newline,
  [48] = 1,
    ACTIONS(43), 5,
      ts_builtin_sym_end,
      anon_sym_i,
      anon_sym_o,
      aux_sym_comment_line_token1,
      sym__newline,
  [56] = 3,
    ACTIONS(45), 1,
      sym_content,
    ACTIONS(47), 1,
      sym_comment,
    ACTIONS(49), 1,
      sym__newline,
  [66] = 3,
    ACTIONS(51), 1,
      sym_content,
    ACTIONS(53), 1,
      sym_comment,
    ACTIONS(55), 1,
      sym__newline,
  [76] = 2,
    ACTIONS(57), 1,
      sym_comment,
    ACTIONS(59), 1,
      sym__newline,
  [83] = 2,
    ACTIONS(61), 1,
      sym_comment,
    ACTIONS(63), 1,
      sym__newline,
  [90] = 1,
    ACTIONS(65), 1,
      sym_datetime,
  [94] = 1,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
  [98] = 1,
    ACTIONS(69), 1,
      sym_datetime,
  [102] = 1,
    ACTIONS(71), 1,
      sym__newline,
  [106] = 1,
    ACTIONS(59), 1,
      sym__newline,
  [110] = 1,
    ACTIONS(73), 1,
      sym__newline,
  [114] = 1,
    ACTIONS(63), 1,
      sym__newline,
  [118] = 1,
    ACTIONS(75), 1,
      sym__newline,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 8,
  [SMALL_STATE(6)] = 16,
  [SMALL_STATE(7)] = 24,
  [SMALL_STATE(8)] = 32,
  [SMALL_STATE(9)] = 40,
  [SMALL_STATE(10)] = 48,
  [SMALL_STATE(11)] = 56,
  [SMALL_STATE(12)] = 66,
  [SMALL_STATE(13)] = 76,
  [SMALL_STATE(14)] = 83,
  [SMALL_STATE(15)] = 90,
  [SMALL_STATE(16)] = 94,
  [SMALL_STATE(17)] = 98,
  [SMALL_STATE(18)] = 102,
  [SMALL_STATE(19)] = 106,
  [SMALL_STATE(20)] = 110,
  [SMALL_STATE(21)] = 114,
  [SMALL_STATE(22)] = 118,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_line, 2, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clock_in, 3, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clock_in, 4, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clock_out, 3, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clock_out, 4, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clock_in, 5, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clock_out, 5, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [67] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_hledger_timeclock(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "hledger_timeclock",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 1,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
